spring:
  application:
    name: yangliuxin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/DB_YANGLIUXIN?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: JUXINTaifu2015
    initialSize: 1
    minIdle: 10
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,log4j,wall
    connectionProperties: druid.stat.mergeSql=true;druid.st
  jpa:
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      format-sql: true
    show-sql: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      indent-output: true
  mvc:
    servlet:
      load-on-startup: 1
    favicon:
      enabled: false
    view:
      prefix: /
      suffix: .html
  redis:
    host: localhost
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  http:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
files:
  path: /weblog/logs/images
token:
  expire:
    seconds: 8640000
  jwtSecret: VIVO_WEDGE2_CN_%^*@#!_2018_&*7876

validate:
  product: Dysmsapi
  domain: dysmsapi.aliyuncs.com
  accessKeyId: LTAIzmtd6XjOmlCs
  accessKeySecret:  Urz2QYFxJI69jh9hK578mciWMO5jaL
  iosAppVersion: 1.0.0
  androidAppVersion: 1.1.0
  code:
    count: 8
    expireIn: 1800

server:
  port: 8000
  tomcat:
      uri-encoding: UTF-8
      basedir: .
      accesslog:
        enabled: true
        directory: /weblog/logs/
        pattern: combined
        prefix: tomcat_access
  servlet-path: /
  #context-path: /boot

#debug: true
logging:
  level: debug
  file: /weblog/logs/yangliuxin.log

flyway:
  enabled: true
  baseline-on-migrate: true
  encoding: UTF-8
  locations: classpath:db/migration

weChat:
  appId: wx2b9b3eacdfadae43
  secret: 67f4e2c2fe77e8cff1e0e29251ada5ba
  token: weChatToken
  expire: 720000
  siteUrl: http://sapi.wedge2.cn/
  gift:
    giftList:
    - {id: 1,name: X23幻彩版, probability: 0.0001, perDay: 1, total: 1}
    - {id: 2,name: 施瓦洛士奇银质项链, probability: 0.001, perDay: 1, total: 20}
    - {id: 3,name: Zack蓝牙音箱, probability: 0.01, perDay: 1, total: 20}
    - {id: 4,name: 爱奇艺会员月卡, probability: 0.01, perDay: 5, total: 300}
    - {id: 5,name: 5元话费(三网通用), probability: 0.2, perDay: 14, total: 800}

shopData:
  url: http://vivo-uat.yjihua.cn:8080/router?
  method: cloud.data.score.dealerscore.query.inf
  # https://retails-service.vivo.xyz