spring:
  application:
    name: yangliuxin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/DB_YANGLIUXIN?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: cae981b191
    initialSize: 1
    minIdle: 10
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,log4j,wall
    connectionProperties: druid.stat.mergeSql=true;druid.st
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      format-sql: true
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      indent-output: true
  mvc:
    servlet:
      load-on-startup: 1
    favicon:
      enabled: false
  redis:
    host: localhost
    port: 6379
    timeout: 20
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  http:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
files:
  path: /weblog/logs/images
token:
  expire:
    seconds: 8640000
  jwtSecret: JellyFish_%^*@#!_2018_&*7876

validate:
  product: Dysmsapi
  domain: dysmsapi.aliyuncs.com
  accessKeyId: LTAIzmtd6XjOmlCs
  accessKeySecret:  Urz2QYFxJI69jh9hK578mciWMO5jaL
  iosAppVersion: 1.0.0
  androidAppVersion: 1.1.0
  code:
    count: 8
    expireIn: 1800

server:
  port: 8000
  tomcat:
      uri-encoding: UTF-8
      basedir: .
      accesslog:
        enabled: true
        directory: /weblog/logs/
        pattern: combined
        prefix: tomcat_access
  servlet-path: /
  #context-path: /boot

#debug: true
logging:
  level: debug
  file: /weblog/logs/yangliuxin.log

flyway:
  enabled: true
  baseline-on-migrate: true
  encoding: UTF-8
  locations: classpath:db/migration
