spring:
  application:
    name: yangliuxin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/DB_YANGLIUXIN?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: yangliuxin
    initialSize: 1
    minIdle: 10
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,log4j,wall
    connectionProperties: druid.stat.mergeSql=true;druid.st
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      format-sql: true
  jackson:
    serialization:
      indent-output: true

server:
  port: 8000
  tomcat:
      uri-encoding: UTF-8
      basedir: .
      accesslog:
        enabled: true
        directory: log
        pattern: combined
        prefix: tomcat_access
  servlet-path: /
  #context-path: /boot

#debug: true
logging:
  level: debug
  file: /weblog/logs/yangliuxin.log

flyway:
  enabled: true
  baseline-on-migrate: true
  encoding: UTF-8
  locations: classpath:db/migration
